version: "3.9"

services:
  kalender:
    image: kalender-app
    container_name: kalender
    restart: unless-stopped

    env_file:
      - .env.dev

    volumes:
      - ./config:/app/config
      - ./Input_data:/app/Input_data
      - ./output:/app/output

